{
 "title": "Patients health metrics dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "patient_id",
    "label": "patient_id",
    "query": "import \"influxdata/influxdb/v1\"\r\nv1.tagValues(\r\n    bucket: \"health_data\",\r\n    tag: \"patient_id\",\r\n    predicate: (r) => true,\r\n    start: -1d\r\n)"
   }
  ]
 },
 "panels": [
  {
   "title": "Body Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"health_data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"health_metrics\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"body_temperature\")\r\n  |> filter(fn: (r) => r.patient_id == \"${patient_id}\")"
    }
   ]
  },
  {
   "title": "SpO2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"health_data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"health_metrics\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"blood_SpO2\")\r\n  |> filter(fn: (r) => r.patient_id == \"${patient_id}\")"
    }
   ]
  },
  {
   "title": "Heart Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"health_data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"health_metrics\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"heart_rate\")\r\n  |> filter(fn: (r) => r.patient_id == \"${patient_id}\")"
    }
   ]
  }
 ]
}